mesh:
  meshFileName: "half_sphere.h5"

gpu: 0 # 0:off , 1:on

solver: "smac" # smac , simple , simplec , fractionalStep

physProp:
  visc : 0.0025 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1004.5 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  last: 
    nStepOuter: 10000
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.0000001
    cfl: 0.30
    dt_min: 0.00000001
    dt_max: 1.0 
  outStepInterval: 100
  timeIntegration: 3  # 1:Euler explicit , 3:3rd Runge Explicit , 10:dual-exp
  implicit:
    nLoop: 100
    cfl_pseudo: 0.5

space: 
  convMethod: 4 # 1:roe, 2:SLAU , 3:keep , 4:AUSM+, 5:AUSM+up

initial: "half_sphere"
