mesh:
  discretization: "node"
  axisCentroidShift: 0
  nodeWallViscGradFlux: 1
  nodeWallDirichlet: 1
  meshFileName: "flat_plate_planar.h5"
  valueFileName: "flat_plate_planar.h5"


gpu: 1 # 0:off , 1:on

solver: "SLAU" # SLAU, ROE, AUSM+, AUSM+UP, KEEP_SLAU

physProp:
  thermalMethod: 0 # 0:calorically perfect
  viscMethod: 0 # 0:use visc , 1:sutherland
  visc : 1.8e-5  # [Pa*s] 空気 (Re/m ~ 2.3e6, M=0.1 で乱流平板)
  thermCond: 0.0251 # [W/(mK)] Pr=0.72 相当
  cp : 1004.5 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time:
  unsteady: 0 # 0:steady , 1:unsteady
  dualTime: 0 # 1:use pseudo time for unsteady
  last:
    nStepOuter: 12000
    time: 1.00 # [second]
  deltaT:
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.0001
    cfl: 20.0
    cfl_pseudo: 3.0 # stage A spinup
    blockDPLUR: 1
    implicitRelax: 0.5
    dt_min: 0.000000001
    dt_max: 1.0
  outStepStart: 0
  outStepInterval: 4000
  timeIntegration: 11  #1:Euler explicit, 3:3rd TVD Runge Explicit, 4:4th runge exp, 10:dual-exp, 11:implicit (block DPLUR)
  nStepInner: 15

space:
  convMethod: 0 # stage A: 1st upwind
  limiter: 2 # 1:barth 2:venkata

turbulence:
  model: "sst"
  wallTreatmentSST: 0 # 1:SST
  scalarDiffusion: 1 # 0:advection-only 1:advection+diffusion
  dilatationCorrection: 0 # low-Mach なので圧縮性補正は off

initial: "flat_plate"
