mesh:
  meshFileName:  "hifire-1.h5"
  valueFileName: "input.h5"

gpu: 1 # 0:off , 1:on

solver: "AUSM+" # SLAU, ROE, AUSM+, AUSM+UP
#solver: "SLAU" # SLAU, ROE, AUSM+, AUSM+UP

physProp:
  visc : 0.000018 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1004.5 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  last: 
    nStepOuter: 500000
    #nStep: 120
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.000000001
    cfl: 0.5
    dt_min: 0.00000000001
    dt_max: 1.0 
  outStepInterval: 5000
  #outStepInterval: 1
  timeIntegration: 3  #1:Euler explicit, 3:3rd TVD Runge Explicit, 4:4th runge exp, 10:dual-exp
  implicit:
    nLoop: 10
    cfl_pseudo: 0.5

space: 
  convMethod: 1
  limiter: 1

initial: "hifire"
