mesh: {meshFormat: "hdf5", discretization: "node", isAxisymmetric: 0, meshFileName: "sern.h5", valueFileName: "sern.h5"}
gpu: 1
solver: "SLAU"
physProp: {isCompressible: 1, thermalMethod: 0, viscMethod: 0, ro: 1.2, visc: 0.0, thermCond: 0.0, cp: 1004.5, gamma: 1.4}
time:
  unsteady: 0
  dualTime: 0
  last: {control: 0, nStepOuter: 600}
  deltaT: {control: 1, dt: 1e-8, cfl: 1.0, cfl_pseudo: 1.0,
           dt_min: 1e-9, dt_max: 0.001, blockDPLUR: 1, lowMachPrecond: 0, detectNaN: 1}
  outStepStart: 0
  outStepInterval: 200
  timeIntegration: 11
  nStepInner: 5
space: {convMethod: 1, limiter: 2, pRef: 4000.0}
turbulence: {model: "none"}
initial: "uniform_p101325_u10"
