mesh:
  meshFileName: "Taylor-Green.h5"
  #meshFormat: "hdf5" 
  #meshFileName: "mach3.h5"


gpu: 0 # 0:off , 1:on

solver: "smac" # smac , simple , simplec , fractionalStep

physProp:
  visc : 0.0025 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 0.4 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  last: 
    nStepOuter: 80000
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.007
    cfl: 0.1
    dt_min: 0.00000001
    dt_max: 1.0 
  outStepInterval: 50
  timeIntegration: 4  #1:Euler explicit, 3:3rd TVD Runge Explicit, 4:4th runge exp, 10:dual-exp
  implicit:
    nLoop: 100
    cfl_pseudo: 0.5

space: 
  convMethod: 3 # 1:roe, 2:SLAU , 3:keep , 4:AUSM

initial: "Taylor-Green_M0.1"
