mesh:
  meshFileName: "test.h5"


gpu: 1 # 0:off , 1:on , -1:gpu check

solver: "smac" # smac , simple , simplec , fractionalStep

physProp:
  #ro : 997 # [kg/m3]
  visc : 0.0025 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1006.0 # [J/(kgK)]

time: 
  last: 
    nStepOuter: 1000
    time: 1.00 # [second]
  deltaT:  
    control: 0 # 0:use dt , 1:use cfl
    dt: 0.02
    cfl: 0.5 
  outStepInterval: 50

space: 
  convMethod: 1 # 1:"1stUp", 2:"2ndUp"

