mesh: {discretization: "node", isAxisymmetric: 0, nodeWallDirichlet: 1, meshFileName: "sern.h5", valueFileName: "sern.h5"}
gpu: 1
solver: "SLAU"
physProp: {thermalMethod: 2, viscMethod: 1, visc: 1.8e-5, thermCond: 0.0257, thermCondMethod: 1, prandtlLam: 0.72, cp: 1718.5, gamma: 1.247, pMin: 20.0, species: ["EXH", "AIR"], speciesDBFile: "species_db.yaml", thermoHrefTemp: 298.15}
time:
  unsteady: 0
  dualTime: 0
  last: {nStepOuter: 6000}
  deltaT: {control: 1, dt: 1e-8, cfl: 0.2, cfl_pseudo: 0.2,
           dt_min: 1e-9, dt_max: 0.001, blockDPLUR: 1, lowMachPrecond: 0, detectNaN: 1}
  outStepStart: 0
  outStepInterval: 3000
  timeIntegration: 11
  nStepInner: 5
space: {convMethod: 0, limiter: 2, pRef: 2851.0, limiterScaled: 1, venkatK: 0.05}
turbulence: {model: "none"}
initial: "uniform_p101325_u10"
