mesh:
  meshFileName: "nozzle_H.h5"
  valueFileName: "nozzle_H.h5"
  #meshFileName: "laval_nozzle3.h5"


gpu: 1 # 0:off , 1:on

solver: "KEEP_AUSM" # SLAU, ROE, AUSM+, AUSM+UP

physProp:
  visc : 0.000018 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1004.5 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  last: 
    nStepOuter: 100000
    #nStep: 100
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.00000001
    cfl: 1.0
    dt_min: 0.000000001
    dt_max: 1.0 
  outStepInterval: 200
  #outStepInterval: 10
  timeIntegration: 3  #1:Euler explicit, 3:3rd TVD Runge Explicit, 4:4th runge exp, 10:dual-exp
  implicit:
    nLoop: 10
    cfl_pseudo: 0.5

space: 
  convMethod: 0 # 0:1stUp 1:2nd 2:MUSCL
  limiter: 1 # 0:off 1:venkata 

initial: "laval"
