mesh:
  meshFileName: "nozzle.h5"
  valueFileName: "nozzle.h5"

gpu: 1
solver: "SLAU"

physProp:
  isAxisymmetric: 1
  thermalMethod: 0
  viscMethod: 1
  visc : 1.8e-5
  thermCond: 0.0257
  cp : 1004.5
  gamma : 1.4

time:
  unsteady: 0
  dualTime: 0
  last:
    nStepOuter: 12000
  deltaT:
    control: 1
    dt: 0.00000001
    cfl: 0.3
    cfl_pseudo: 0.3
    dt_min: 0.000000001
    dt_max: 0.001
  outStepStart: 0
  outStepInterval: 3000
  timeIntegration: 3
  nStepInner: 1

space:
  convMethod: 1
  limiter: 2

turbulence:
  model: "sst"
  scalarDiffusion: 1
  dilatationCorrection: 2
  kInf: 1.0
  omegaInf: 1000.0

initial: "uniform_p101325_u10"
