inlet:  {physID: 1, kind: inlet_Pressure, outputHDFflg: 0, ints: , floats: {Pt: 104190.0, Tt: 302.4, k: 7.87, omega: 3401.0}}
outlet: {physID: 2, kind: outlet_statPress, outputHDFflg: 0, ints: , floats: {Ps: 101325.0, Pt: 104190.0, Tt: 302.4}}
top:    {physID: 3, kind: slip, outputHDFflg: 0, ints: , floats: }
wall:   {physID: 4, kind: wall, outputHDFflg: 1, ints: , floats: {Ux: 0.0, Uy: 0.0, Uz: 0.0}}
sym:    {physID: 5, kind: slip, outputHDFflg: 0, ints: , floats: }
