mesh:
  meshFileName: "cavity.h5"

gpu: 0 # 0:off , 1:on

solver: "smac" # smac , simple , simplec , fractionalStep

physProp:
  #ro : 997 # [kg/m3]
  visc : 0.0025 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1006.0 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  last: 
    nStepOuter: 100
    time: 1.00 # [second]
  deltaT:  
    control: 0 # 0:use dt , 1:use cfl
    dt: 0.0001
    cfl: 0.5 
  outStepInterval: 1

space: 
  convMethod: 3 # 1:"roe", 2:"SLAU" , 3:"keep"

