mesh: {meshFileName: "tg.h5", valueFileName: "tg.h5"}
gpu: 1
solver: "SLAU"
physProp: {thermalMethod: 0, viscMethod: 0,visc: 0.0, thermCond: 0.0, cp: 1004.5, gamma: 1.4}
time:
  unsteady: 0
  dualTime: 0
  last: {nStepOuter: 300, time: 1.0}
  deltaT: {control: 1, dt: 1.0e-8, cfl: 0.5, cfl_pseudo: 2.0, dt_min: 1.0e-9, dt_max: 1.0, blockDPLUR: 0, implicitRelax: 1.0, lowMachPrecond: 0, detectNaN: 1}
  outStepStart: 0
  outStepInterval: 50
  timeIntegration: 3
  nStepInner: 1
space: {convMethod: 0, limiter: 2, pRef: 101325.0}
turbulence: {model: "none"}
initial: "Taylor-Green"
