inlet:
  physID: 1
  kind: inlet_uniformVelocity
  outputHDFflg: 0
  ints:
  floats:
    Ux: 458.6
    Uy: 0.0
    Uz: 0.0
    ro: 11.733
    Ps: 617800.0
    k: 31.547
    omega: 3.0018e7
outlet:
  physID: 2
  kind: outlet_statPress
  outputHDFflg: 0
  ints:
  floats:
    Ps: 1700000.0
    Pt: 1700000.0
    Tt: 288.15
wall_slip:
  physID: 3
  kind: slip
  outputHDFflg: 0
  ints:
  floats:
wall:
  physID: 4
  kind: wall
  outputHDFflg: 1
  ints:
  floats:
