mesh:
  meshFileName: "naca2412_with_box.h5"
  #valueFileName: "input.h5"
  valueFileName: "naca2412_with_box.h5"


gpu: 1 # 0:off , 1:on

#solver: "KEEP_SLAU" # SLAU, ROE, AUSM+, AUSM+UP, KEEP_SLAU
solver: "SLAU" # SLAU, ROE, AUSM+, AUSM+UP, KEEP_SLAU
#solver: "ROE" # SLAU, ROE, AUSM+, AUSM+UP, KEEP_SLAU

physProp:
  thermalMethod: 0 # 0:calorically perfect
  viscMethod: 0 # 0:use visc , 1:sutherland
  visc : 0.000018  #[Pa*s]
  #visc : 0.00  #[Pa*s]
  thermCond: 0.0257 # [W/(mK)]
  cp : 1004.5 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  unsteady: 1 # 0:steady , 1:unsteady
  dualTime: 0 # 1:use pseudo time for unsteady
  last: 
    nStepOuter: 100000
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl 
    dt: 0.00000001
    cfl: 1.5
    cfl_pseudo: 1.0 # for pseudo dt
    dt_min: 0.000000001
    dt_max: 1.0 
  outStepStart: 0
  outStepInterval: 1000
  timeIntegration: 3  #1:Euler explicit, 3:3rd TVD Runge Explicit, 4:4th runge exp, 10:dual-exp
  nStepInner: 10

space: 
  convMethod: 2 # 0:1stUp 1:2ndup 2:MUSCL
  limiter: 2 # 1:barth 2:venkata

turbulence:
  model: "none"

initial: "supercritical"

